### ISSUE TITLE
No port opening inside the container

### ISSUE THREAD

**Issue by asyscom** [bitvora/haven#10]
Hi, I started the relay via Docker, and I can see the exposed port on 0.0.0.0 is 3335 (the guide mentions 3355, and I'm not sure if that's an issue). I've placed the container on the same network as Nginx, and when I inspect it, I can see the correct IP. However, from inside Nginx, the telnet connection doesn't close, and when I run an nmap scan, it doesn't detect any port listening. Additionally, from the outside, if I try a telnet to the server's public IP on port 3335, it doesn't close the connection.

[root@docker-1fc4d997890c:/app]# nmap 172.18.0.3
Starting Nmap 7.93 ( https://nmap.org ) at 2024-09-25 07:30 UTC
Nmap scan report for haven-relay.nextcloud_network (172.18.0.3)
Host is up (0.0000080s latency).
All 1000 scanned ports on haven-relay.nextcloud_network (172.18.0.3) are in ignored states.
Not shown: 1000 closed tcp ports (reset)
MAC Address: 02:42:AC:12:00:03 (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 0.21 seconds

Thanks in advance

**Comment by barrydeen** [comment]
should be fixed now, please pull the latest and try
