### ISSUE TITLE
cotaine crashes every day due to aws error

### ISSUE THREAD

**Issue by asyscom** [bitvora/haven#26]
Hello, the container crashes every day due to an AWS code error. In the .env file, I commented out the AWS part because I don’t use it. How can I resolve this? Below is the error log. Thank you.

2024/10/02 11:54:45 operation error S3: PutObject, https response error StatusCode: 403, RequestID: E1JZY68RN80PJR87, HostID: ZQjn4i5L1tujyLdFoDGeqaQCKh5CCFaNOWmklScyNoMDctIRqKul8hB3ohxIXA0lUEYVBQtVZlAaBIRoQIsxBg==, api error InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

**Comment by asyscom** [comment]
> yeah. it would be good to allow s3 compatible backends or completely disable the function

I've disabled AWS Backup, but the container continues to crash with the same error: 2024/10/03 14:48:27 operation error S3: PutObject, https response error StatusCode: 403, RequestID: 51KAM43AVP90R43T, HostID: JO3y8PMT72rGLNDs1ksfv6pbF2dxO0UF+piobLG+d90fhViGkNZTlnd9exAaFQ0nf1pD/YOlz2M=, API error InvalidAccessKeyId: The AWS Access Key ID you provided does not exist in our records.

This is the part about AWS Backup. I’ve obviously restarted Docker after making the modification.

## Backup Settings
#BACKUP_PROVIDER="aws"
#BACKUP_INTERVAL_HOURS=24

## AWS Backup Settings - REQUIRED IF BACKUP_PROVIDER="aws"
#AWS_ACCESS_KEY_ID="AKIA"
#AWS_SECRET_ACCESS_KEY="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
#AWS_REGION="us-west-2"
#AWS_BUCKET_NAME="utxo-relay-backups"

**Comment by eleaner** [comment]
I confirm it also crashes daily if I provide bogus credentials to AWS

**Comment by asyscom** [comment]
Any news about this problem? it's impossible to use with this bug

**Comment by eleaner** [comment]
for me it kind of works between crashes

**Comment by barrydeen** [comment]
fixed in #31 , please update to the latest and set your .env backup provider to "none" or just leave it blank
