### ISSUE TITLE
Import apparently stuck after owner note import complete

### ISSUE THREAD

**Issue by ciori** [bitvora/haven#28]
I tried to run `./haven --import` but the process seems to be stuck after completing the import of owner notes and no other log is displayed.

![haven-logs](https://github.com/user-attachments/assets/1cae27b4-fb26-4975-a5ac-b116c5d7f739)

The first part of the import took nearly 10 minutes (from 2022-06-01 just to be sure to be able to import all the notes, 06 is the month) and then I waited more than half an hour but nothing happened. I also tried to increase the log level but nothing is displayed.

I followed the standard non-docker setup.

**Comment by barrydeen** [comment]
what is your npub?

**Comment by ciori** [comment]
npub1hupmmajeu337x9t54lmknr8c8dxdsx430q5uytmatn8hd74vmw7s6unnm6

**Comment by barrydeen** [comment]
please try the upcoming version by doing

`git checkout v0.4.0`

it should solve it, let me know

**Comment by ciori** [comment]
Can confirm the v0.4.1 tag is working, thanks.
