### ISSUE TITLE
ws:// relsys don't work

### ISSUE THREAD

**Issue by eleaner** [bitvora/haven#29]
Hello
the documentation says
"The JSON should contain an array of relay URLs (without ws:// or wss://):"

I try to add ws:// onion-relay 
however it looks like the code just adds wss:// to each relay - so it naturally fails with message
`error connecting to relay <nil> failed to connect: error opening websocket to 'wss://xxxx.onion': failed to dial: dial tcp: lookup xxx.onion on 185.12.64.1:53: no such host`
both the container and the vm can resolve xxxx.onion
container uses host networking

easy to reproduce trying to blast to local relay without ssl

**Comment by HolgerHatGarKeineNode** [comment]
You cannot use Tor/Onion relays within your list, since they are not using SSL (wss://) and the container cannot open .onion Urls.

**Comment by eleaner** [comment]
If container uses host network and host network is fully torified opening onions should not be a problem Fixed prefix wss:// isOn 8 Oct 2024, at 16:05, The Ben 'notifications at github.com' ***@***.***> wrote:﻿
You cannot use Tor/Onion relays within your list, since normally they are not using SSL (wss://) and the container cannot open .onion Urls.

**Comment by barrydeen** [comment]
This is fixed in #33 - you can use `git checkout v0.4.0` to run it now before we merge into master

simply set the the protocol in the .json files
