### ISSUE TITLE
building wot seems failing randomly

### ISSUE THREAD

**Issue by eleaner** [bitvora/haven#30]
```
2024/10/07 21:25:52 🔗 listening at http://localhost:3355
2024/10/07 21:25:55 🌐 building web of trust graph
2024/10/07 21:26:11 🫂 total network size: 1219
2024/10/07 21:26:11 🔗 relays discovered: 156
2024/10/07 21:26:11 🌐 pubkeys with minimum followers:  227 keys
2024/10/07 21:26:11 📢 subscribing to inbox
```
and just a few min later
```
2024/10/07 21:26:58 🌐 building web of trust graph
2024/10/07 21:27:14 🫂 total network size: 13696
2024/10/07 21:27:14 🔗 relays discovered: 444
2024/10/07 21:27:14 🌐 pubkeys with minimum followers:  9799 keys
2024/10/07 21:27:14 📢 subscribing to inbox
```

the log does not provide any more information but i assume just like with blastr it just randomly fails on any relay and stops moving forward.

**Comment by barrydeen** [comment]
there must be a log, can you please provide the output of `sudo journalctl -u haven -n 1000`

**Comment by eleaner** [comment]
It’s docker, and what i pasted is part of decker log - unless i am missing setting of some logging level Sent from my iPhoneOn 8 Oct 2024, at 16:03, Barry Deen 'notifications at github.com' ***@***.***> wrote:﻿
there must be a log, can you please provide the output of sudo journalctl -u haven -n 1000

**Comment by barrydeen** [comment]
I see. please retry without docker. docker support will be removed next week in 0.4.0 as outlined in #33 

unfortunately nobody was willing to provide docker support and it's causing too many issues

closing for now, please reopen if you continue to get this issue running it bare metal

**Comment by eleaner** [comment]
lol, oh man
you make it too difficult for me :)

**Comment by HolgerHatGarKeineNode** [comment]
@eleaner https://github.com/HolgerHatGarKeineNode/haven-docker

and pre-built docker images here: https://hub.docker.com/r/holgerhatgarkeinenode/haven-docker

**Comment by eleaner** [comment]
you guys are amazing!
