### ISSUE TITLE
db permissions

### ISSUE THREAD

**Issue by pailakapo** [bitvora/haven#41]
After install, trying to import using:
`./haven --import`
I got
`panic: Invalid Dir: "db/private" error: stat db/private: permission denied
`
because:
`$ ls -la
total 30932
drwxr-xr-x 5 haven haven     4096 Oct 20 07:07 .
drwx------ 7 haven haven     4096 Oct 20 07:05 ..
-rw-r--r-- 1 haven haven     2217 Oct 20 06:45 backup.go
-rw-r--r-- 1 haven haven      503 Oct 20 06:45 blastr.go
-rw-r--r-- 1 haven haven     7066 Oct 20 06:45 config.go
drwx------ 6 root  root      4096 Oct 20 07:07 db
`

is the db supposed to be root only, and does this import command need to be run as root?

**Comment by pailakapo** [comment]
following the install instructions, the systemctl service runs the service as root, which is why the db is created as root, and not accessible by the user installing the relay.  Is this the desired behavior?

I changed the permissions to user haven for db and now I get a different error trying to import:

$ ./haven --import

██╗  ██╗ █████╗ ██╗   ██╗███████╗███╗   ██╗
██║  ██║██╔══██╗██║   ██║██╔════╝████╗  ██║
███████║███████║██║   ██║█████╗  ██╔██╗ ██║
██╔══██║██╔══██║╚██╗ ██╔╝██╔══╝  ██║╚██╗██║
██║  ██║██║  ██║ ╚████╔╝ ███████╗██║ ╚████║
╚═╝  ╚═╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═══╝
HIGH AVAILABILITY VAULT FOR EVENTS ON NOSTR
	
2024/10/21 08:29:37 🚀 haven is booting up
panic: Cannot acquire directory lock on "db/private".  Another process is using this Badger database. error: resource temporarily unavailable

goroutine 1 [running]:
main.initRelays()
	/home/haven/haven/init.go:114 +0x1505
main.main()
	/home/haven/haven/main.go:33 +0x1ae

**Comment by derekross** [comment]
chmod -R user:group ./db

I personally run the systemd process as a different user.
Derek Ross
https://NostrPlebs.com
https://NostrPlebs.com/s/derekross

**Comment by barrydeen** [comment]
Stop your systems service

Then chmod -R 777 db/

Then run import

Then start systemd
