### ISSUE TITLE
mixed up port numbers

### ISSUE THREAD

**Issue by eleaner** [bitvora/haven#5]
I love it
but I realised that:

the app listens on 3355
Docker file exposes 3334
docker-compose and torrc refer to 3335

**Comment by HolgerHatGarKeineNode** [comment]
In recent versions of Dockerfile, EXPOSE [typically](https://docs.docker.com/engine/reference/builder/#expose) doesn't have any operational impact anymore, it is just informative. ([see also](https://stackoverflow.com/a/65785558/5075502))

But I will correct that tomorrow.
