### ISSUE TITLE
Known Issues with LMDB and Badger

### ISSUE THREAD

**Issue by aaccioly** [bitvora/haven#57]
Currently some users have reported issues with LMDB on Windows, macOS and some arm64 Linux distros due to khatru's default mapsize value (~273GB) exceeding their max disk space.

Other users are reporting panics with Badger,  e.g., see https://github.com/bitvora/wot-relay/issues/79#issuecomment-2495943496.

**Comment by aaccioly** [comment]
@cr0bar, would you mind testing this version / branch? I don't have access to a bare metal Debian box, but it is working fine for me on a Debian Bookworm container + go1.23.3 - https://github.com/aaccioly-open-source/haven/tree/fix/db-patches

**Comment by aaccioly** [comment]
@girino, same thing for LMDB + Windows with the new `LMDB_MAPSIZE` parameter. It worked well for me on macOS.

**Comment by cr0bar** [comment]
> @cr0bar, would you mind testing this version / branch? I don't have access to a bare metal Debian box, but it is working fine for me on a Debian Bookworm container + go1.23.3 - https://github.com/aaccioly-open-source/haven/tree/fix/db-patches

Tested on bookworm bare metal and working again as expected.

**Comment by aaccioly** [comment]
Many thanks. As soon as someone confirms that LMDB is working on Windows, I'll open a PR :).

**Comment by girino** [comment]
with default values i get this:

C:\cygwin64\tmp\haven>main.exe

```
2024/11/26 09:11:46 🚀 haven is booting up
panic: mdb_env_open: There is not enough space on the disk.

goroutine 1 [running]:
main.initRelays()
        C:/cygwin64/tmp/haven/init.go:71 +0x2e8e
main.main()
        C:/cygwin64/tmp/haven/main.go:37 +0x20b
```

setting the LMDB_MAPSIZE to 10737418240 (10GB) and it runs smoothly!

```
2024/11/26 09:14:34 🔗 listening at 0.0.0.0:3355
2024/11/26 09:14:49 🌐 building web of trust graph
2024/11/26 09:15:35 🫂 total network size: 27184
2024/11/26 09:15:35 🔗 relays discovered: 524
2024/11/26 09:15:36 🌐 pubkeys with minimum followers:  19012 keys
2024/11/26 09:15:36 🚫 no backup provider set
2024/11/26 09:15:36 📢 subscribing to inbox
```

So problem with lmdb solved on windows too.
