### ISSUE TITLE
404 page not found under HTTP

### ISSUE THREAD

**Issue by eleaner** [bitvora/haven#6]
does the relay is supposed to be not accessible thought HTTP?
or it is it still loading events (in which case it could be useful to serve HTTP earlier)

Cheers

**Comment by HolgerHatGarKeineNode** [comment]
Why? It is a personal relay?!

**Comment by eleaner** [comment]
yes, personal
I have an impression that haven is personal,
right?

**Comment by barrydeen** [comment]
fixed now.
